swagger: "2.0"
info:
  title: "world-of-wordcraft-Springboot"
  version: "1.0"
host: "localhost"
schemes: 
- "http"
basePath: "/api"
paths: 
  /{gameType}/count:
    get:
      tags:
      - "tag"
      summary: "get count for given gameType"
      produces: 
      - "application/json"
      parameters:
      - name: "gameType"
        in: "path"
        description: "GameType identifies which wordlist to use for the operation"
        required: true
        type: "string"
      responses:
       "200":
        description: "successful operation"
  /{gameType}/random:
    get:
      tags:
      - "tag"
      summary: "get random word for given gameType"
      produces: 
      - "application/json"
      parameters:
      - name: "gameType"
        in: "path"
        description: "GameType identifies which wordlist to use for the operation"
        required: true
        type: "string"
      responses:
       "200":
        description: "successful operation"
  /{gameType}/list:
    get:
      tags:
      - "tag"
      summary: "get whole list for given gameType"
      produces: 
      - "application/json"
      parameters:
      - name: "gameType"
        in: "path"
        description: "GameType identifies which wordlist to use for the operation"
        required: true
        type: "string"
      responses:
       "200":
        description: "successful operation"
securityDefinitions:
security:
  - 

  
definitions:
  gameType:
   type: "string"
   description: "gameType defines what wordlist to use"
   enum:
   - "EN"
   - "DE"